### ISSUE TITLE
Missing comma on example config file in Readme

### ISSUE THREAD

**Issue by majordomo-systems** [ch99q/nuxt-pdf#17]
Hi, just letting you know there is a missing comma in the example config (puppeteer options)

**Comment by sadortun** [comment]
Fixed in https://github.com/ch99q/nuxt-pdf/commit/fc90d05376444b6b6e0e7715401ed16f24cf031c#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
