### ISSUE TITLE
I can not start

### ISSUE THREAD

**Issue by SkiperX** [ch99q/nuxt-pdf#4]
Sorry. Did everything by readme. I can not get the pdf of the main page. A regular page opens.

https://github.com/SkiperX/example

**Comment by ch99q** [comment]
Hello @SkiperX, I actually have a newer version that is tested I will push up, I can just first do it tomorrow due to my files is on a backup at work! 😄

**Comment by ch99q** [comment]
I will get this working with an example as fast as I can!

**Comment by ch99q** [comment]
I'm unable to open your example? Also, this repository might not work at this point. But will look into it, but to solve the issue you have to open your repository.

**Comment by SkiperX** [comment]
oh, remade it in public

**Comment by ch99q** [comment]
@SkiperX Try to change the version to 1.0.3, the module was missing a dependency.
Sorry, it took so long, have been a busy week!
