### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by SBarros013** [ch99q/nuxt-pdf#5]
Hello! I really like this package and want to use on a project. But I don't get how to use this. I follow all steps of configuration but I need to know how to trigger the function to generate the pdf.

Can you help me, please?

**Comment by ch99q** [comment]
@SBarros013 can you give it a try now?

**Comment by SBarros013** [comment]
Still not working for me. I don't know if i'm doing something wrong.

That's my nuxt-config (I added 'nuxt-pdf' on modules)
![image](https://user-images.githubusercontent.com/34045735/75732828-5e1bf700-5cd2-11ea-83be-80def34c3c45.png)

And that's my vue template
![image](https://user-images.githubusercontent.com/34045735/75732973-c1a62480-5cd2-11ea-85c4-32dbbd1c6582.png)

There are anything else I have to do? Sorry if i'm being a dumb...

**Comment by ch99q** [comment]
Are you using `nuxt build` or `nuxt generate` to generate the website, because it's only made for static generation aka `nuxt generate`

**Comment by ch99q** [comment]
@SBarros013

**Comment by SBarros013** [comment]
I'm using nuxt build to generate. So that's the problem! Thank you!
