### ISSUE TITLE
Request to add Demo / Example page

### ISSUE THREAD

**Issue by amit-soni7** [ch99q/nuxt-pdf#6]
This repo looks promising. Author added how to add nuxt-pdf as module in nuxt.config.js file.
but readme.md does not clarify how to use nuxt-pdf in .vue file or .js file.

 Please give some example/demo about usage of nuxt-pdf in .vue file.

**Comment by AdrianoCahete** [comment]
You need to build the Nuxt with `nuxt generate` (or `npm run generate`)

**Comment by isuke01** [comment]
so it works only with Generate?

**Comment by AdrianoCahete** [comment]
Seems to be, yes. I had another problem with not generating PDF after that: #7

**Comment by ch99q** [comment]
Added a playground folder, with a basic example using the module.

@isuke01 The new version will work with `nuxt dev`, `nuxt build` and `nuxt generate` 😉

There were some breaking changes in the new version, read what to here: https://github.com/ch99q/nuxt-pdf/issues/7#issuecomment-672811940

**Comment by isuke01** [comment]
Thanks for reply 👍
